### ISSUE TITLE
flutter integration

### ISSUE THREAD

**Issue by joeblew99** [Appointy/Jaal#1]
Hey,

I was just playing with thunder and found your graphql implementation. It look really clean.

Does the flutter library work with Jaal ? I have not tried yet.

**Comment by Shivam010** [comment]
Yes
You can use any framework or library you want. In the end, Jaal just creates a server that handles POST requests.

See the example [server](https://github.com/appointy/jaal/blob/master/example/wizard/main.go)

**Comment by Shivam010** [comment]
We are developing flutter client for jaal.
It is under development and will be soon released.
